### ISSUE TITLE
Fatal Exception: java.util.ConcurrentModificationException for userProperties

### ISSUE THREAD

**Issue by dpprequel** [apphud/ApphudSDK-Android#34]
```
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:757)
       at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:790)
       at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:788)
       at com.apphud.sdk.ApphudInternal.updateUserProperties(ApphudInternal.java:532)
       at com.apphud.sdk.ApphudInternal.access$getParser$p(ApphudInternal.java:24)
       at com.apphud.sdk.ApphudInternal$registration$1$1.run(ApphudInternal.java:164)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8051)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
```

После того, как начали использовать userProperties стали получать некоторое количество падений с таким стектрейсом. 
Версия библиотеки на данный момент 0.8 (но посмотрел исходники, для самой последней вроде не менялся принципиально мехазнизм работы с userProperties, думаю проблема сохранилась)

**Comment by vladimir-slatvinskiy** [comment]
Fixed in v.1.3.9
