### ISSUE TITLE
Apphud SDK crashes app after being called via onProductDetailsResponse by Billing library

### ISSUE THREAD

**Issue by tlozovyi** [apphud/ApphudSDK-Android#95]
Started seeing this issue after updating Apphud SDK from v2.3.3 to v2.6.6.
Still seeing it with v2.7.0.

The issue is not limited to any particular device.

Affected Android versions from 9 up to 14.

```
Fatal Exception: java.lang.IllegalStateException: Already resumed, but proposed with update (null, 2)
       at kotlinx.coroutines.CancellableContinuationImpl.alreadyResumedError(CancellableContinuationImpl.kt:555)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:520)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:493)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:364)
       at com.apphud.sdk.internal.ProductDetailsWrapper$querySync$2$1$1.onProductDetailsResponse(ProductDetailsWrapper.kt:159)
       at com.android.billingclient.api.BillingClientImpl.zzZ(BillingClientImpl.java:3)
       at com.android.billingclient.api.zzao.run(zzao.java:2305)
       at com.android.billingclient.api.zzy.run(zzy.java:4)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by ren6** [comment]
Fixed in latest SDK versions, thanks!
